SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';



ALTER TABLE `chinoixeofadmon`.`banks` 
ADD COLUMN `initial balance` DECIMAL(10,2) NULL DEFAULT NULL AFTER `rfc`,
ADD COLUMN `cheq_num_start` INT(11) NULL DEFAULT NULL AFTER `initial balance`,
ADD COLUMN `cheq_num_end` INT(11) NULL DEFAULT NULL AFTER `cheq_num_start`,
ADD COLUMN `consecutive` INT(11) NULL DEFAULT NULL AFTER `cheq_num_end`;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
